# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AKMediaUBox' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'Masonry', '~> 1.0.2'

  # Pods for AKMediaUBox

  target 'AKMediaUBoxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AKMediaUBoxUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
